### ISSUE TITLE
Laravel 5.1 support?

### ISSUE THREAD

**Issue by Ardakilic** [rtconner/laravel-likeable#10]
Hello,

Are there any plans to implement the package to Laravel 5.1 ?

Would altering the composer requirements suffice?

Thanks,

**Comment by rtconner** [comment]
It should work with 5.1 already. Hrm. I'll check over the weekend, or make a pull request if you know of any specific code fixed needed for this.

**Comment by Ardakilic** [comment]
Altering `composer.json`'s requirements would suffice I guess. I can make a pull request if you'd like to.

**Comment by rtconner** [comment]
release 1.0.8
