### ISSUE TITLE
Problem in vendor publishing in laravel 5.2

### ISSUE THREAD

**Issue by bdtiger** [rtconner/laravel-likeable#12]
I am using `laravel 5.2`. I have added    `'Conner\Likeable\LikeableServiceProvider'` in providers array in `config/app.php`
When I have run this command 
`php artisan vendor:publish --provider="Conner\Likeable\LikeableServiceProvider"`
I have got  `Nothing to publish for tag [].` I have also tried after removing vendor folder and composer.lock file. But nothing changed.

Is this package is not compatible for `laravel 5.2`?

**Comment by jabedbd** [comment]
i'm also facing the same problem on Laravel 5.2.

**Comment by rtconner** [comment]
This should be fixed in 1.1.0 release. Thanks for reporting the issue.
