### ISSUE TITLE
Publish Issue

### ISSUE THREAD

**Issue by timgavin** [rtconner/laravel-likeable#17]
There's an issue when publishing

```
php artisan vendor:publish --provider="Conner\Likeable\LikeableServiceProvider" --tag=migrations
```

Which results in

```
Nothing to publish for tag [migrations]
```

**Comment by rtconner** [comment]
Are you on the latest version of this package? 1.2

**Comment by timgavin** [comment]
Yes. From my composer.json file's require: `"rtconner/laravel-likeable": "~1.2"`

**Comment by alexsnkr** [comment]
I have the same issue..I'm also using version 1.2

**Comment by rtconner** [comment]
I think this has something to do with $defer and caching. 
Anyways, can you try version 1.2.1 out and see if it's good now?

**Comment by timgavin** [comment]
It's good, thank you.
