### ISSUE TITLE
Likeable while being anonymous

### ISSUE THREAD

**Issue by gregory-claeyssens** [rtconner/laravel-likeable#20]
I would like to know what the implications would be if anonymous users would be able to 'like' models.

My idea would be to save the id's and Model name's in the session. If a user would then make an account (and thus not be anonymous anymore) the session 'likes' would be transferred.

I'm more then willing to create a pr for this, i'm just wondering what your thought are about this.

Thank you in advance.

**Comment by rtconner** [comment]
Just do $article->like(0); to like without having a user. It' adds to the like count but does not link to a user.

please see the documentation - https://github.com/rtconner/laravel-likeable/blob/laravel-5/README.md

**Comment by gregory-claeyssens** [comment]
I'm sorry, maybe my explanation was not clear. I still want to be able to fetch a user's likes, even though he is not really a user (not authenticated). For example a 'my favorites' page where they can review all their favorites.
That's why I was thinking Session's

**Comment by rtconner** [comment]
Oh if you want some sort of session storage on here you would have to build it yourself. This is just open source code, I'm not building every little feature that everyone wants. If you do build something nice, feel free to make a pull request back into this repository (as long as you have unit test coverage)

**Comment by GregoryClaeyssens** [comment]
Thank rtconner, I'm not expecting you to do anything, I'm going to reference my initial post (again).

**Comment by rtconner** [comment]
Ok my bad. I didn't read that clearly.

I'm sure it would be a lot of work to have it toggle seamlessly between session and database storage. Might be easier to just add likeSession() and unlikeSession() type methods to the trait and then listSessionLikes() or something along that lines. I can't think of any way to build it otherwise without substantial updates to a lot of code.

A toggle between database and session storage seems pretty complex, especially in trying to handle the joins in the queries.

**Comment by gregory-claeyssens** [comment]
Thank you @rtconner

**Comment by rtconner** [comment]
I feel like your best option might be to build your own library to function to spec as you need, and just copy/paste code from here when you find it useful.

**Comment by gregory-claeyssens** [comment]
Hi @rtconner , thanks for the advice, I used quite a bit of code from you. 
The package is viewable [here](https://github.com/sugar-agency/laravel-likeable)
If you would change your mind and want to 'merge' the 2, I'm open to it

**Comment by rtconner** [comment]
Why did you use the same name :) ha. Get your own package name.
I like that console tool. I'm still unsure about that session stuff being part of this package.
