### ISSUE TITLE
package `whereLiked` function conflicting with Eloquent syntax in 5.2

### ISSUE THREAD

**Issue by UnrulyNatives** [rtconner/laravel-likeable#22]
The below code worked for me in 5.1.

`$object = Excerpt::whereLiked(Auth::id()) // find only articles where user liked them
            ->remember(1024)
            ->with('likeCounter') // highly suggested to allow eager load
            ->paginate(30);`

Now I get 

`QueryException in Connection.php line 680:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'liked' in 'where clause' (SQL: select count(*) as aggregate from`quotations`where`liked`= 5 and`deepness`>= 0)`

What should we do?

Thank you, 
Peter

**Comment by catoruno** [comment]
I have the same error SQLSTATE[42703]: Undefined column: 7 ERROR: no existe la columna «liked», any idea where i can resolve this issues.

Thank you.
Carlos

**Comment by brentarcane** [comment]
Looks like the docs need updating.  Using whereLikedBy on your Likeable model works.

For example:

`Article::whereLikedBy($myUserId); // find only articles where user liked them`

**Comment by rtconner** [comment]
Thank you , updated the Readme.
