### ISSUE TITLE
New trait "Conner\Likeable\Likeable" is not working for me

### ISSUE THREAD

**Issue by Vongsi** [rtconner/laravel-likeable#29]
Hi Creator and contributors

I really like this package and appreciated your great works.

I installed the package using: composer require rtconner/laravel-likeable "~1.2"

It seems the new trait name "Conner\Likeable\Likeable" is not working, so I tried the old one "Conner\Likeable\LikeableTrait" and it is working. 

I checked in src and it is updated there,

`<?php
namespace Conner\Likeable;
/**
 * Copyright (C) 2014 Robert Conner
 */
trait Likeable
{`

How can it did not work for me ? 

Thanks

**Comment by TheAudiogram** [comment]
I am experiencing this issue as well. Laravel could not find 'Likeable', however reverting to the prior naming convention 'LikeableTrait' solved the issue.

**Comment by trinvh** [comment]
The code in this repo is different to composer install. So that's why Likable class not found.
In composer.json file (in project root), the version is missing.
