### ISSUE TITLE
Best way to orderBy likes?

### ISSUE THREAD

**Issue by robertem128** [rtconner/laravel-likeable#32]
Hi, 

I didn't see anything in the docs about ordering posts by like count so I thought I'd ask.

Currently, i'm using 
````
->withCount('likes')
->orderBy('likes_count', 'desc')
````
Is this the recommended way?

Thanks

**Comment by rtconner** [comment]
That seems correct

**Comment by robertem128** [comment]
Great. Thanks for your work on this, it was very helpful in my project.

**Comment by ismailcaakir** [comment]
Thanks, this works really well.
