### ISSUE TITLE
Semantic versioning.

### ISSUE THREAD

**Issue by mikebronner** [rtconner/laravel-likeable#36]
Hi @rtconner,

I did read the documentation about the change in version 1.3.0. However, this should have been marked as version 2.0.0, to adhere to semantic versioning, as this is a backward breaking change. Would you consider making the version jump to protect against these breaking changes?

Thanks!

**Comment by rtconner** [comment]
Sure no problem, I'll do it tonight.

Should I delete version 1.3 or keep it?

**Comment by mikebronner** [comment]
Thanks @rtconner. That's a tough call. If people have 1.3 specified as their min version, it will break, at which point they will be forced to take a look at it. On the other hand, if you keep 1.3 around, it will break for those who have 1.2 or lower, and they won't know it breaks, because they might not be doing the update (the server might provision with 1.3, whereas it would not provision with 2.0. I'm inclined to say remove the 1.3. What do you think?

**Comment by rtconner** [comment]
I think the person who did the laravel 6 version literally checked out the `laravel-5` branch, edited it and mad a PR back into it. OMG. How :(
