### ISSUE TITLE
Upgrading to latest version, migration error

### ISSUE THREAD

**Issue by crysfel** [rtconner/laravel-likeable#38]
Hi there!

I'm trying to migrate to the latest version, the database already has the tables that were created before but it looks like when running a migration it tries to run the migration to create the tables again from the vendors folder.

```
$ php artisan migrate
Migrating: 2016_02_07_000000_create_likeable_tables

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'likeable_likes' already exists
```

The migrations fails because the table already exist, any idea how can I ignore running this migration? Is not even on my `database/migrations` it looks like ` php artisan migrate` is looking into `vendor/rtconner/laravel-likeable/` and trying to run the migration there.

If I manually delete that migration, everything seems to work, but I'm worried it will fail when my deployment script will try to run the migrations when deploying to production.

Thanks in advance!

**Comment by rtconner** [comment]
I don't have a nice way to fix this. You will probably have to manually fix the scripts and structure.

**Comment by crysfel** [comment]
I end it up checking if the table exist before running the migration, something like this:

```
                if (!Schema::hasTable('likeable_likes')) {
			Schema::create('likeable_likes', function(Blueprint $table) {
				$table->increments('id');
				$table->string('likable_id', 36);
				$table->string('likable_type', 255);
				$table->string('user_id', 36)->index();
				$table->timestamps();
				$table->unique(['likable_id', 'likable_type', 'user_id'], 'likeable_likes_unique');
			});
		}
```
