### ISSUE TITLE
Dislike function

### ISSUE THREAD

**Issue by ortix** [rtconner/laravel-likeable#4]
What about a "dislike" function? I think that would be a nice addition. So that way people can like, dislike, unlike and undislike.

**Comment by UnrulyNatives** [comment]
+1

**Comment by Pandahisham** [comment]
+1

**Comment by k1ng440** [comment]
+1

**Comment by rtconner** [comment]
Any comments on if like and dislike should be mutually exclusive, i.e., you cannot like and dislike something at the same time?

**Comment by k1ng440** [comment]
Yes. 

If liked by the user, { dislike removes the like count }
if disliked by the user, { like removes the dislike count }
else add count to like/dislike

**Comment by ortix** [comment]
+1 mutually exclusive

**Comment by liorocks** [comment]
+1

**Comment by evsign** [comment]
+1 mutually exclusive. And maybe rating attribute, which is difference of likes and dislikes.

**Comment by rtconner** [comment]
Apparently I'm never going to build this. It's free code, and I don't need the feature myself. 

If someone wants this, they'll have to create their own package, or do the changes needed to this package.
