### ISSUE TITLE
Update of docs

### ISSUE THREAD

**Issue by UnrulyNatives** [rtconner/laravel-likeable#5]
You might consider adjusting the docs with the below information. 
To make a model likeable the below lines should be added:

```
use Conner\Likeable\LikeableTrait;
class Quotation extends Model  {

use LikeableTrait;
```

Note, that in Laravel 5 class declaration the Eloquent is replaced by Model

**Comment by mstnorris** [comment]
@UnrulyNatives have you got it working? I get Class 'Eloquent' not found, which as you suggest is because Model is used now.

**Comment by UnrulyNatives** [comment]
it works perfectly in my projects - after I made the changes. of course.

**Comment by mstnorris** [comment]
What changes were those? I am in the process of changing them at the moment.

**Comment by mstnorris** [comment]
@UnrulyNatives do you know how to get the names of the people who like something when using

$article->likes ??

**Comment by rtconner** [comment]
Hrm.. you would have to do like 

``` php
foreach($article->likes as $like) {
    $user = User::find($like->user_id);
}
```

Which I don't love.  I may upgrade the code to make that easier in the future.

**Comment by mstnorris** [comment]
@rtconner That'd be great :)

**Comment by rtconner** [comment]
Ya, thanks for the idea.

**Comment by UnrulyNatives** [comment]
Whouldn't be enough just to add the below function in the model?

```
public function liker()
{
    return $this->belongsTo('App\Models\User', 'creator_id');
}
```

then, to get list of likers in view file

```
@foreach($article->likers as $like) 
    {{$like->username}}
```

Anyway, the dislikes proposed in the other ticket would be much more desired, if you asked me. :)

**Comment by AlexKomMsk** [comment]
It can be done like this
```
    $userIds = [];

    foreach ($comment->likes as $like) {
      $userIds[] = $like->user_id;
    }

    $users = User::with('profile')
                      ->whereIn('id', $userIds)
                      ->get();
```

**Comment by juniorfrogie** [comment]
> Whouldn't be enough just to add the below function in the model?
> 
> ```
> public function liker()
> {
>     return $this->belongsTo('App\Models\User', 'creator_id');
> }
> ```
> 
> then, to get list of likers in view file
> 
> ```
> @foreach($article->likers as $like) 
>     {{$like->username}}
> ```
> 
> Anyway, the dislikes proposed in the other ticket would be much more desired, if you asked me. :)

Does it work when I want to a list of users who liked the post?
