### ISSUE TITLE
Class 'Eloquent' not found when calling $article->likeCount;

### ISSUE THREAD

**Issue by dambridge** [rtconner/laravel-likeable#7]
Looking at your Tag code, I added the following to Like.php and it resolved:

From:

```
class LikeCounter extends \Eloquent {...
```

To:

```
use Illuminate\Database\Eloquent\Model as Eloquent;

class LikeCounter extends Eloquent {...
```

**Comment by rtconner** [comment]
Right that's laravel 4 only syntax above. I've modified the docs to show better L5 samples.

**Comment by rtconner** [comment]
Ooops I see what you meant. Ok fixed.

**Comment by dambridge** [comment]
Woot, thanks!
